### PR TITLE
Adding Photo-Z estimation problem from HSC

### PR DESCRIPTION
**Pull request by EiffL**
This pull request implements a Photo-z estimation problem using HSC PDR2 data. It essentially queries all matches between spectroscopic sample and PDR2 wide data, and extract postage stamps in all 5 bands.

Before merging it, would just need to solve the following issues
- [x] : Check that the sample selection is OK, in particular, I'm using a FDFC cut that isn't mentioned in the first HSC paper. not sure whether it's a good thing.
- [x] : Use upstream version of Unagi to do the query
- [x] : Export a version of the dataset to a storage facility for quick download

@dr-guangtou Would you have time to look at the sample selection done here: https://github.com/ml4astro/galaxy2galaxy/blob/u/EiffL/hsc_photoz/galaxy2galaxy/data_generators/hsc_utils/queries/hsc_pdr2_wide_photoz.sql 
Check if that makes sense...

### CODE REVIEW

**Comment by kstoreyf** [comment]
I discussed this FDFC cut with Song at one point and I think the result was
that the internal cut wasn't decided yet, so they've been using 3 as
minimum for all bands. But would also like to confirm this / see if there's
an update!

**Comment by dr-guangtou** [comment]
@EiffL The SQL search looks fine to me. 

One small thing is about the specz error: 

`AND specz.specz_redshift_err < 0.005*(1 + specz.specz_redshift)`

These errors are from different surveys. I think Tanaka-san just compiled these errors together. They could mean different things and sometimes error message is not available.  I would just keep the `specz_redshift_err` in the output and check them later.

**Comment by dr-guangtou** [comment]
@kstoreyf There is an "official" FDFC mask now for the internal S18A release, which is basically the PDR2.  The mask file is not in public, and I will ask for the criteria used to generate it. 

For earlier release, the final mask involves criteria about PSF modeling since it is designed for weak lensing analysis.  I think the `inputvalue > 3` in all 5-bands is a good starting point for this project.

**Comment by EiffL** [comment]
Thanks both! I've updated the SQL query to just remove the cut on redshift error, and updated the dependency link in the setup.py to install unagi from the  main repo, now that https://github.com/dr-guangtou/unagi/pull/14 has been merged.

Next step is to run the dataset script and export the result of the query to some server so that people don't have to wait around 24h for it to run :-)

**Review by EiffL — COMMENTED** [review]
LGTM, thanks past EiffL

**Pull request merged**
